# Advanced Programme in Deep Learning (Foundations and Applications)
## A Program by IISc and TalentSprint
### Assignment 4: Linear Algebra

## Learning Objectives

At the end of the assignment, you will be able to

*   understand rank of a matrix
*   implement SVD (Singular Value Decomposition) using Python
*   understand vector and matrix norm
*   perform various matrix calculus operations using Python



### Setup Steps:

In [4]:
#@title Please enter your registration id to start: { run: "auto", display-mode: "form" }
Id = "2236006" #@param {type:"string"}

In [5]:
#@title Please enter your password (normally your phone number) to continue: { run: "auto", display-mode: "form" }
password = "9968251058" #@param {type:"string"}

In [6]:
#@title Run this cell to complete the setup for this Notebook
from IPython import get_ipython
import warnings
warnings.filterwarnings("ignore")

ipython = get_ipython()
  
notebook= "M1_AST_04_Linear_Algebra_A" #name of the notebook

def setup():
    from IPython.display import HTML, display
    display(HTML('<script src="https://dashboard.talentsprint.com/aiml/record_ip.html?traineeId={0}&recordId={1}"></script>'.format(getId(),submission_id)))
    print("Setup completed successfully")
    return

def submit_notebook():
    ipython.magic("notebook -e "+ notebook + ".ipynb")
    
    import requests, json, base64, datetime

    url = "https://dashboard.talentsprint.com/xp/app/save_notebook_attempts"
    if not submission_id:
      data = {"id" : getId(), "notebook" : notebook, "mobile" : getPassword()}
      r = requests.post(url, data = data)
      r = json.loads(r.text)

      if r["status"] == "Success":
          return r["record_id"]
      elif "err" in r:        
        print(r["err"])
        return None        
      else:
        print ("Something is wrong, the notebook will not be submitted for grading")
        return None
    
    elif getAnswer1() and getAnswer2() and getComplexity() and getAdditional() and getConcepts() and getComments() and getMentorSupport():
      f = open(notebook + ".ipynb", "rb")
      file_hash = base64.b64encode(f.read())

      data = {"complexity" : Complexity, "additional" :Additional, 
              "concepts" : Concepts, "record_id" : submission_id, 
              "answer1" : Answer1, "answer2" : Answer2, "id" : Id, "file_hash" : file_hash,
              "notebook" : notebook,
              "feedback_experiments_input" : Comments,
              "feedback_mentor_support": Mentor_support}
      r = requests.post(url, data = data)
      r = json.loads(r.text)
      if "err" in r:        
        print(r["err"])
        return None   
      else:
        print("Your submission is successful.")
        print("Ref Id:", submission_id)
        print("Date of submission: ", r["date"])
        print("Time of submission: ", r["time"])
        print("View your submissions: https://dlfa-iisc.talentsprint.com/notebook_submissions")
        #print("For any queries/discrepancies, please connect with mentors through the chat icon in LMS dashboard.")
        return submission_id
    else: submission_id
    

def getAdditional():
  try:
    if not Additional: 
      raise NameError
    else:
      return Additional  
  except NameError:
    print ("Please answer Additional Question")
    return None

def getComplexity():
  try:
    if not Complexity:
      raise NameError
    else:
      return Complexity
  except NameError:
    print ("Please answer Complexity Question")
    return None
  
def getConcepts():
  try:
    if not Concepts:
      raise NameError
    else:
      return Concepts
  except NameError:
    print ("Please answer Concepts Question")
    return None
  
  
# def getWalkthrough():
#   try:
#     if not Walkthrough:
#       raise NameError
#     else:
#       return Walkthrough
#   except NameError:
#     print ("Please answer Walkthrough Question")
#     return None
  
def getComments():
  try:
    if not Comments:
      raise NameError
    else:
      return Comments
  except NameError:
    print ("Please answer Comments Question")
    return None
  

def getMentorSupport():
  try:
    if not Mentor_support:
      raise NameError
    else:
      return Mentor_support
  except NameError:
    print ("Please answer Mentor support Question")
    return None

def getAnswer1():
  try:
    if not Answer1:
      raise NameError 
    else: 
      return Answer1
  except NameError:
    print ("Please answer Question 1")
    return None

def getAnswer2():
  try:
    if not Answer2:
      raise NameError 
    else: 
      return Answer2
  except NameError:
    print ("Please answer Question 2")
    return None
  

def getId():
  try: 
    return Id if Id else None
  except NameError:
    return None

def getPassword():
  try:
    return password if password else None
  except NameError:
    return None

submission_id = None
### Setup 
if getPassword() and getId():
  submission_id = submit_notebook()
  if submission_id:
    setup() 
else:
  print ("Please complete Id and Password cells before running setup")



Setup completed successfully


### Importing the required libraries

In [7]:
import numpy as np
import scipy
import sympy as sym
import matplotlib.pyplot as plt
from sympy.abc import x, y,z
from scipy import linalg

### Rank of a Matrix


**Rank of a matrix**: - The rank of a matrix is defined as the maximum number of linearly independent column vectors in the matrix or the maximum number of linearly independent row vectors in the matrix.



**Full Row Rank**:- If the rank of a matrix is equal to the number of row in the matrix, then matrix has a Full Row Rank.

**Full Column Rank**:- If the rank of a matrix is equal to the number of columns in the matrix, then matrix has Full Column Rank.


**Rank Deficient**:-When the rank of a matrix is less than the number of rows and columns in the matrix, then the matrix is Rank Deficient.

**Uses**:-
It is useful in understanding whether we have a chance of solving a system of linear equations or not. Further, if rank is equal to the number of variables we will be able to find a unique solution.


1. Create a random matrix and find the rank of it.

    Refer to the following [link](https://numpy.org/doc/stable/reference/generated/numpy.linalg.matrix_rank.html) to find the rank of a matrix

In [8]:
# YOUR CODE HERE: To create a matrix
M = np.array([[np.arange(1,4)],[np.arange(14,17)]])
#M
# YOUR CODE HERE: To find the rank of a matrix
np.linalg.matrix_rank(M)

array([1, 1])

### Singular Value Decomposition

The Singular-Value Decomposition, or SVD is a matrix decomposition method for reducing a matrix to its constituent parts in order to make certain subsequent matrix calculations simpler. The singular value decomposition (SVD) provides another way to factorize a matrix, into singular vectors and singular values. The SVD allows us to discover some of the same kind of information as the eigendecomposition.

Steps to follow for Singular Value Decomposition

  A. Factorize a matrix using SVD 

  B. Reconstruct the original matrix

**A. Matrix Factorization:**

In simple terms, SVD is the factorization of a matrix into 3 matrices. So if we have a matrix A, then its SVD is represented by:
<center>
$A = U ∑ V^{T}$
</center>

Where A is an $m$ x $n$ matrix,  

*   $U$ is an $m$ x $m$ orthogonal matrix
*   $∑$ is an $m$ x $n$ diagonal matrix with non-negative real numbers.
*   $V$ is an $n$ x $n$ orthogonal matrix.


$U$ is also referred to as the left singular vectors, $∑$ the singular values, and $V$ the right singular vectors.

**B. Reconstruct the original matrix from SVD:**

The original matrix can be reconstructed from the $U$, Sigma, and $V^{T}$ elements.



1. Create an array of $2$ x $3$ matrix and apply singular value decompostition on it.




> The SVD can be calculated by calling the `svd()` function from `numpy.linalg`.

> The function takes a matrix and returns the $U$, Sigma and $V^{T}$ elements. The Sigma diagonal matrix is returned as a vector of singular values. The $V$ matrix is returned in a transposed form, e.g. $V^{T}$.











In [9]:
# YOUR CODE HERE: Define a matrix
M = np.random.randint(10, size = (2,3))
# YOUR CODE HERE: To apply ingular Value Decomposition on the matrix
u, s, vh = np.linalg.svd(M)
# YOUR CODE HERE: Create m x n matrix called sigma
sigma = np.zeros((M.shape[0], M.shape[1]))
#print(sigma)
# YOUR CODE HERE: Populate sigma with n x n diagonal matrix
sigma[ :M.shape[0], :M.shape[0]] = np.diag(s)

# YOUR CODE HERE: To Reconstruct the original matrix
B= u.dot(sigma.dot(vh))
print(M, B)

[[8 2 7]
 [0 8 2]] [[8.00000000e+00 2.00000000e+00 7.00000000e+00]
 [9.12899631e-16 8.00000000e+00 2.00000000e+00]]


### Matrix and Vector Norms

**Matrix Norm**: The norm of a matrix is a measure of how large its elements are. It is a way of determining the “size” of a matrix that is not necessarily related to how many rows or columns the matrix has.

The norm of a square matrix A is a non-negative real number denoted $\left \| A \right \|$. There are several
different ways of defining a matrix norm, but they all share the following properties:
1. $\left \| A \right \|$ ≥ 0 for any square matrix A.
2. $\left \| A \right \|$ = 0 if and only if the matrix A = 0.
3. $\left \| kA \right \|$ = |k| $\left \| A \right \|$, for any scalar k.
4. $\left \| A+B \right \|$ ≤ $\left \| A \right \|$ + $\left \| B \right \|$.
5. $\left \| AB \right \|$ ≤ $\left \| A \right \|$ $\left \| B \right \|$.

Below is the formula to calculate 1 norm of a matrix:

$\left \| A \right \|_{1} = \max_{1≤j≤n} (\sum_{i}^{n} \left | a_{ij} \right |)$

By using this formula we compute the sum of absolute values down each column
and then take the largest number.



1. Calculate the 1-norm of a matrix $A =\begin{pmatrix}
    5 & -4 & 2\\
    -1 & 2 & 3\\
    -2 & 1 & 0\\
   \end{pmatrix}$. 

   Refer to the following [link ](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html) to understand norm function in numpy's linalg module


In [10]:
# Creating a matrix
# YOUR CODE HERE
A = np.array([[np.arange(12,15)], [np.arange(3,6)], [np.arange(21,24)]])
M = np.array([[ 5, -4, 2],
			[-1, 2, 3],
      [-2, 1, 0]])
print(A, M)
# 1-Norm of a matrix
# The 1-Norm of a matrix is the maximum of the sum of each column
# Pass the matrix to the norm function and specify the order
# YOUR CODE HERE
#np.linalg.norm(M, 1)
matrix_norm = np.linalg.norm(M, 1)
matrix_norm

[[[12 13 14]]

 [[ 3  4  5]]

 [[21 22 23]]] [[ 5 -4  2]
 [-1  2  3]
 [-2  1  0]]


8.0

**Vector Norm**: The norm of a vector in vector space is a real non-negative value representing intuitively the length, size, or magnitude of the vector.

The most commonly used vector norms belong to the family of $p$-norms, or $l_{p}$-norms, which
are defined by:
<center>
$\left \| x \right \|_{p} = (\sum_{i = 1}^{n} |x_{i}|^{p}) ^ {1/p}$
</center>

It can be shown that for any $p > 0$,  $∥ ⋅ ∥_{p}$ defines a vector norm. The following $p$-norms are of
particular interest:


*   $p = 1$: The $l_{1}$-norm
<center>
$∥ x ∥_{1} =  |x_{1}| +  |x_{2}| +....+ |x_{n}| $ 
</center>

*   $p = 2$: The $l_{2}$-norm or Euclidean norm
<center>
$\left \| x \right \|_{2}= \sqrt{x_{1}^{2}+x_{2}^{2}+...+x_{n}^{2}}$
</center>

* $p = ∞$: The $l_{∞}$-norm
<center>
$\left \| x \right \|_{∞}= \max_{1\leq i \leq n} |x_{i}|$.
</center>


1. Compute the norm of a given vector $A = [5,12]$.

In [11]:
# Creating a matrix
# YOUR CODE HERE
A = [[5,12]]
print(A)
print(np.array([5,12]))
# L2-Norm of a vector
# YOUR CODE HERE
np.linalg.norm(A, 2)
#np.linalg.norm(np.array([5,12]), 2)

[[5, 12]]
[ 5 12]


13.0

### Matrix Calculus



### 1. Dervatives w.r.t. Scalar

#### Scalar w.r.t Scalar





1. Differentiate the below given scalar function $f(x)$ w.r.t. to a scalar $x$.

  $ f(x) = \cos x + \sin x + x^2 $

In [12]:
# Declaring symbols that can be used as variables in the function
# YOUR CODE HERE
import math
first = sym.cos(x)
second = sym.sin(x)
third = x**2
# Defining a function 'f'
# YOUR CODE HERE
f = (first + second + third)
# Derivative of the scalar function w.r.t. a scalar x using the 'diff' function of Sympy
# YOUR CODE HERE
sym.diff(f, x)

2*x - sin(x) + cos(x)

#### Vector w.r.t. Scalar

2. Differentiate the given vector $\vec{y}^{\,} = \begin{pmatrix}
    x^2 + 2x \\
    sinx \\
    cosx \\
   \end{pmatrix}$ w.r.t. a scalar $x$.

  Note: `Vector` is a special case of `Matrix`




In [13]:
# YOUR CODE HERE
y = sym.Matrix([[x**2 + 2*x], [sym.sin(x)], [sym.cos(x)]])

y.diff(x)

Matrix([
[2*x + 2],
[ cos(x)],
[-sin(x)]])

#### Matrix w.r.t. Scalar

3. Find the derivative of the matrix $M = \begin{pmatrix}
    x^2 + 2x & cos(x)\\
    sin(x) & x^3+2x\\
   \end{pmatrix}$ w.r.t. a scalar $x$.




In [14]:
# YOUR CODE HERE

y = sym.Matrix([[x**2 + 2*x, sym.cos(x)],[sym.sin(x), x**3 + 2*x]])
y
y.diff(x)

Matrix([
[2*x + 2,    -sin(x)],
[ cos(x), 3*x**2 + 2]])

Before moving ahead with more questions on derivatives w.r.t. vectors and matrices, you should have knowledge of "Partial Derivatives", "Jacobian Matrix" and "Numerator Layout Notation". 

### Partial Derivatives

Let us consider a function $f(x,y) = x^2 + y^2$ we can take a derivative of the changes in the function with respect to either x or y. We call these derivatives with respect to one variable partial derivatives. Let's give this a try by taking the derivative of $f(x,y)$ with respect to x. We write this partial derivative as follows.

$$\frac{\partial f(x,y)}{\partial x} = \frac{\partial (x^2 + y^2)}{\partial x}$$

Since $f(x,y)$ is the sum of several simpler functions we need to take the partial derivative of each of these and sum the result. The first two parts are easy. $\frac{\partial x^2}{\partial x} = 2x$. Notice that we are following the usual rules of differentiation for any function of x here.

Now we need to take the partial derivative of the last part of $f(x,y)$, which does not depend on x at all. In these case we get the following $\frac{\partial y^2}{\partial x} = 0$. 
Now we can add up the parts to get the complete partial derivative of $f(x,y)$.

$$\frac{\partial f(x,y)}{\partial x} = 2x + 0 = 2x$$
We can also take the partial derivative of $f(x,y)$ with respect to y. The process proceeds in the following manner $\frac{\partial f(x,y)}{\partial y} = 0 + 2y = 2y$

### Jacobian Matrix

To test for functional dependence (both linear and non linear equations) between different equations we use Jacobian determinant shown by |j|. The Jacobian matrix is the first order derivatives of a vector valued function. Vector valued functions are defined as $f: \mathbb{R}^n \to \mathbb{R}^m$.

Given $x \in \mathbb{R}^n$ and $f_j : \mathbb{R}^n \to \mathbb{R}$ we have

$$f(x) = \begin{bmatrix}
    f_1(x) \\
    f_2(x) \\
    \vdots \\
    f_m(x)
\end{bmatrix}$$
 
 We could then define the jaccobian  as 
 
 $$J(x) = \begin{bmatrix}
    \frac{\partial f_1}{\partial x_1} & \frac{\partial f_1}{\partial x_2}  & \dots  & \frac{\partial f_1}{\partial x_n} \\
    \frac{\partial f_2}{\partial x_1} & \frac{\partial f_2}{\partial x_2}  & \dots  & \frac{\partial f_2}{\partial x_n}  \\
    \vdots & \vdots & \ddots & \vdots \\
    \frac{\partial f_m}{\partial x_1} & \frac{\partial f_m}{\partial x_2}  & \dots  & \frac{\partial f_m}{\partial x_n} 
\end{bmatrix} $$
 
Hence each row represents the derivative of a real valued function with input vectors. Note that using shape convention we must reshape that to have the same output as the vector input. 

Let's find the derviate of function $f(x, y) = x + sin(y) $ with respect to x and y

In [15]:
# Defining x and y as symbols
# YOUR CODE HERE
x, y = sym.symbols('x, y')
f = x + sym.sin(y)
f
# Defining the function f(x, y)
# YOUR CODE HERE

x + sin(y)

In [16]:
# Derivate w.r.t to 'x'
# YOUR CODE HERE
f.diff(x)
# Derivate w.r.t to 'y'
# YOUR CODE HERE
f.diff(y)

cos(y)

If we organize these partials into a horizontal vector, we get the gradient of $f(x, y)$, or $\Delta f(x, y)$ :

$ \Delta f(x,y)  = [\frac{\partial f(x,y)}{\partial x}, \frac{\partial f(x,y)}{\partial y}] = [1, cos(y)] $

In [17]:
# YOUR CODE HERE
delta = [f.diff(x), f.diff(y)]
delta

[1, cos(y)]

Now let's find the derviate of function $g(x, y) = sin(x) + y $ with respect to x and y

In [18]:
# Defining the function g(x, y)
# YOUR CODE HERE
g = sym.sin(x) + y
g

y + sin(x)

In [19]:
# Derivate w.r.t to 'x'
# YOUR CODE HERE
g.diff(x)
# Derivate w.r.t to 'y'
# YOUR CODE HERE
g.diff(y)

1

If we organize these partials into a horizontal vector, we get the gradient of $g(x, y)$, or  $Δg(x,y)$:

$ \Delta g(x,y)  = [\frac{\partial g(x,y)}{\partial x}, \frac{\partial g(x,y)}{\partial y}] = [cos(x), 1] $

In [20]:
# YOUR CODE HERE
delta_g = [g.diff(x), g.diff(y)]

If we organize the gradients of $f(x, y)$ and $g(x, y)$ into a single matrix, we move from vector calculus into matrix calculus. This matrix, and organization of the gradients of multiple functions with multiple variables, is known as the Jacobian matrix.

$ J = \begin{bmatrix}
\Delta f(x,y) \\
\Delta g(x,y) \end{bmatrix} =\begin{bmatrix}
\frac{\partial f(x, y)}{\partial x} & \frac{\partial f(x, y)}{\partial y}\\ 
\frac{\partial g(x, y)}{\partial x} & \frac{\partial g(x, y)}{\partial y}
\end{bmatrix} = \begin{bmatrix}
1 & cos(y) \\ 
cos(x) & 1
\end{bmatrix} $

To know more about the Jacobian Matrix read [here](https://towardsdatascience.com/step-by-step-the-math-behind-neural-networks-d002440227fb)

In [21]:
# YOUR CODE HERE
j = sym.Matrix([delta, delta_g])
j

Matrix([
[     1, cos(y)],
[cos(x),      1]])

### Numerator Layout Notation: 

This approach is used when we have to find the derivative w.r.t. a vector. Using Numerator Layout Notation, we find the partial derivative of a scalar, matrix, or a vector w.r.t. each element of the vector.
<br>Suppose, there is a vector $\vec{x}^{\,}$ = ($x_{1}$, $x_{2}$, $x_{3}$,.... $x_{n}$) w.r.t. which we have to find the derivative of a scalar function or a matrix.
<br>For this, we will take the partial derivative of the scalar function or a matrix w.r.t. each element of the vector as shown below:

$\frac{\partial}{\partial_x}$ = $\left (\frac{\partial}{\partial_(x_{1})}, \frac{\partial}{\partial_(x_{2})}, \frac{\partial}{\partial_(x_{3})}  \right )$


### 2. Dervatives w.r.t. Vector

#### Scalar by Vector

1. Given a scalar function $y = \tan(x^2+yz)$. Find the derivative of $y$ w.r.t. the below vector:

  $\vec{v}^{\,}(x,y,z)$ = $xyz$

  Hint: Apply numerator layout notation where we take derivative of the function w.r.t. every element of the vector. 



In [25]:
# Defining symbols that will be used as variables in the function
# YOUR CODE HERE
x, y, z = sym.symbols('x, y, z')
# Defining a scalar function using the symbols x, y and z
# YOUR CODE HERE
vec = x*y*z
scalar_func = sym.tan(x**2 + y*z)

Differentiating the scalar function w.r.t. each element of the vector i.e. x, y, and z

In [28]:
# YOUR CODE HERE
dx, dy, dz = scalar_func.diff(x), scalar_func.diff(y), scalar_func.diff(z)
dx, dy, dz

(2*x*(tan(x**2 + y*z)**2 + 1),
 z*(tan(x**2 + y*z)**2 + 1),
 y*(tan(x**2 + y*z)**2 + 1))

#### Matrix by Vector

2. Find the derivative of the below matrix $M$ w.r.t. vector $\vec{v}^{\,}$ = $ xyz$:

\begin{pmatrix}
    x+x^2z & cosx\\
    xyz & 3y+x^2\\
   \end{pmatrix}



In [33]:
# Defining the matrix M
# YOUR CODE HERE
M = sym.Matrix([[x + x*x*z, sym.cos(x)], [x*y*z, 3*y + x*x]])
M
# Differentiating matrix 'M' w.r.t. each element of the vector v that are x, y, z
# YOUR CODE HERE
dx, dy, dz = M.diff(x), M.diff(y), M.diff(z)
# Result -> Organizing the result of partial derivatives into a single matrix
# YOUR CODE HERE
output = sym.Matrix([dx, dy, dz])
output

Matrix([
[2*x*z + 1, -sin(x)],
[      y*z,     2*x],
[        0,       0],
[      x*z,       3],
[     x**2,       0],
[      x*y,       0]])

#### Vector by Vector

3. Find the derivative of vector $\vec{v}^{\,}$ = $\begin{pmatrix}
   cosx+x\\
    x^2+y^2\\
    3x^3-z^2y\\
   \end{pmatrix}$ w.r.t. a vector $\vec{k}^{\,}$ = $xyz$

In [36]:
# Defining the vector v 
# YOUR CODE HERE
vec_v = sym.Matrix([sym.cos(x)+x, x**2+y**2, 3*x**3-x**2*y])
vec_v
# Vector k = xyz indicates that we have to differentiate vector 'v' w.r.t. x, y, and z
# YOUR CODE HERE
dx, dy, dz = vec_v.diff(x), vec_v.diff(y), vec_v.diff(z)
# Result -> Organizing the result of partial derivatives into a single matrix
# YOUR CODE HERE
result = sym.Matrix([dx, dy, dz])
result

Matrix([
[    1 - sin(x)],
[           2*x],
[9*x**2 - 2*x*y],
[             0],
[           2*y],
[         -x**2],
[             0],
[             0],
[             0]])

### 3. Dervatives w.r.t. Matrix

#### Scalar by Matrix
To find the derivative of a scalar w.r.t. a matrix, we have to find the derivative of the scalar function w.r.t. every element of the matrix to get the final result.
<br> Further, let us understand with th help of a question.

1. Find the derivative of a scalar $y = (sinx_{1}+2x_{2}+x_{3}^2+7x_{4})$ w.r.t. a matrix $M = \begin{pmatrix}
   x_{1} & x_{2}\\
    x_{3} & x_{4}\\
   \end{pmatrix}$.

In [37]:
# Defining the symbols for the matrix M
# YOUR CODE HERE
x1, x2, x3, x4 = sym.symbols('x1, x2, x3, x4')
# Defining a scalar function using the symbols declared above which are used as variables
# YOUR CODE HERE
scalar_y = sym.sin(x1) + 2*x2 + x3**2 + 7*x4
# Defining a matrix
# YOUR CODE HERE
M = sym.Matrix([[x1, x2], [x3, x4]])
# Differentiation of scalar function w.r.t. every element of the matrix 
# YOUR CODE HERE
dx1, dx2, dx3, dx4 = scalar_y.diff(x1), scalar_y.diff(x2), scalar_y.diff(x3), scalar_y.diff(x4)
# Organizing the result of partial derivatives into a single matrix
# YOUR CODE HERE
results = sym.Matrix([dx1, dx2, dx3, dx4])
results

Matrix([
[cos(x1)],
[      2],
[   2*x3],
[      7]])

#### Matrix by Matrix
Here, we have to find the derivative of the given matrix w.r.t. each element of the matrix by which we have to differentiate.
<br> Let us solve a question to understand derivative of a matrix wr.r.t. a matrix.

2. Find the derivative of a matrix $A$ = $\begin{pmatrix}
   x_{1}^2+x_{2}^2+x_{2} & x_{2}^2+x_{4}^2\\
    sinx_{2}+x_{3}^2 & x_{1}+x_{3}+x_{4}\\
   \end{pmatrix}$  w.r.t. a matrix $M = \begin{pmatrix}
   x_{1} & x_{2}\\
    x_{3} & x_{4}\\
   \end{pmatrix}$.

In [38]:
# Defining the matrix A
# YOUR CODE HERE
A = sym.Matrix([[x1**2+x2**2+x2, x2**2+x4**2],[sym.sin(x2)+x3**2, x1+x3+x4]])
# Defining matrix M
# YOUR CODE HERE
M = sym.Matrix([[x1, x2], [x3, x4]])
# Differentiating matrix A w.r.t. each element of matrix M
# YOUR CODE HERE
dx1, dx2, dx3, dx4 = A.diff(x1), A.diff(x2), A.diff(x3), A.diff(x4)
# Organizing the result of partial derivatives into a single matrix
# YOUR CODE HERE
outout = sym.Matrix([dx1, dx2, dx3, dx4])
outout

Matrix([
[    2*x1,    0],
[       0,    1],
[2*x2 + 1, 2*x2],
[ cos(x2),    0],
[       0,    0],
[    2*x3,    1],
[       0, 2*x4],
[       0,    1]])

#### Vector by Matrix
As vector is a special case of matrix, so, we will consider the vector as a matrix while finding the derivative using Python. 

3. Find the derivative of vector $\vec{m}^{\,}$ = $\begin{pmatrix}
   sinx_{1}+x_{2}\\
    x_{3}^2+x_{2}^2\\
    2x_{2}+x_{4}\\
   \end{pmatrix}$ w.r.t. the matrix $M = \begin{pmatrix}
   x_{1} & x_{2}\\
    x_{3} & x_{4}\\
   \end{pmatrix}$.

In [43]:
# YOUR CODE HERE
vector_m = sym.Matrix([[sym.sin(x1)+x2],[x3**2+x2**2],[2*x2+x4]])
vector_m
dx1, dx2, dx3, dx4 = vector_m.diff(x1), vector_m.diff(x2), vector_m.diff(x3), vector_m.diff(x4)
sym.Matrix([dx1, dx2, dx3, dx4])

Matrix([
[cos(x1)],
[      0],
[      0],
[      1],
[   2*x2],
[      2],
[      0],
[   2*x3],
[      0],
[      0],
[      0],
[      1]])

In [54]:
A = sym.Matrix([[4, 11, 14], [8, 7 , -2]])
AT = sym.Transpose(A)
#print(A)
iden_lam = x*(np.identity(3))
#print(iden_lam)
final_matrix = AT*A - iden_lam
sym.det(final_matrix)

-1.0*x**3 + 450.0*x**2 - 32400.0*x

### Question for practice (Ungraded)

Q. The derivative of a matrix $A = \begin{pmatrix}
    x^4 & x^2+2x\\
    xyz & cos(x)\\
   \end{pmatrix}$ w.r.t. a scalar $x$.

a) $\begin{pmatrix} 4x^2 & 2\\ 1 & sin(x)\\ \end{pmatrix} $

b) $\begin{pmatrix}
    x^3 & x^2+2x\\
    xyz & cos(x)\\
   \end{pmatrix}$

c) $\begin{pmatrix}
    4x^3 & 2x+2\\
    yz & -sin(x)\\
   \end{pmatrix}$

d) $\begin{pmatrix}
    4x^3 & x\\
    1 & -cos(x)\\
   \end{pmatrix}$

Ans) c

### Please answer the questions below to complete the experiment:




#### Consider the below matrix 'A' and the values of $σ_{1}$, $σ_{2}$, $σ_{3}$ given below for answering Q.1

<br>
$A = \begin{pmatrix}
   4 & 11 & 14\\
    8 & 7 & -2\\
   \end{pmatrix}$

<br>
<br>

A. $σ_{1} = {{360}}$, $σ_{2} = {{90}}$, $σ_{3} = 0$

B. $σ_{1} = {6\sqrt{10}}$, $σ_{2} = {3\sqrt{10}}$, $σ_{3} = 0$

C. $σ_{1} = {-6\sqrt{10}}$, $σ_{2} = {3\sqrt{10}}$, $σ_{3} = {{0}}$

D. $σ_{1} = {6\sqrt{10}}$, $σ_{2} = {{0}}$, $σ_{3} = {-3\sqrt{10}}$




In [55]:
#@title Q.1. Find the singular values for the above matrix 'A' { run: "auto", form-width: "500px", display-mode: "form" }
Answer1 = "Only B" #@param ["","Only A", "Only B", "Only C", "Only D", "None of the above"]


Consider the below column values $v_{1}$, $v_{2}$, $v_{3}$ and $v_{4}$ and answer Q.2

A. $v_{1} = \begin{pmatrix}
   1/3\\
    2/3\\
     2/3\\
   \end{pmatrix}$

B.  $v_{2} = \begin{pmatrix}
   -2/3\\
    -1/3\\
     2/3\\
   \end{pmatrix}$

C.  $v_{3} = \begin{pmatrix}
   2/3\\
    -2/3\\
     1/3\\
   \end{pmatrix}$

D. $v_{4} = \begin{pmatrix}
   2/3\\
    2/3\\
     1/3\\
   \end{pmatrix}$

In [56]:
#@title Q.2. Find the normalized eigenvector corresponding to the highest eigenvalue obtained in question 1 by computing A^TA? { run: "auto", form-width: "500px", display-mode: "form" }
Answer2 = "None of the above" #@param ["","Only A", "Only B", "Only C", "Only D", "None of the above"]


In [57]:
#@title How was the experiment? { run: "auto", form-width: "500px", display-mode: "form" }
Complexity = "Good and Challenging for me" #@param ["","Too Simple, I am wasting time", "Good, But Not Challenging for me", "Good and Challenging for me", "Was Tough, but I did it", "Too Difficult for me"]


In [58]:
#@title If it was too easy, what more would you have liked to be added? If it was very difficult, what would you have liked to have been removed? { run: "auto", display-mode: "form" }
Additional = "" #@param {type:"string"}


In [59]:
#@title Can you identify the concepts from the lecture which this experiment covered? { run: "auto", vertical-output: true, display-mode: "form" }
Concepts = "Yes" #@param ["","Yes", "No"]


In [60]:
#@title  Text and image description/explanation and code comments within the experiment: { run: "auto", vertical-output: true, display-mode: "form" }
Comments = "Somewhat Useful" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]


In [61]:
#@title Mentor Support: { run: "auto", vertical-output: true, display-mode: "form" }
Mentor_support = "Didn't use" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]


In [62]:
#@title Run this cell to submit your notebook for grading { vertical-output: true }
try:
  if submission_id:
      return_id = submit_notebook()
      if return_id : submission_id = return_id
  else:
      print("Please complete the setup first.")
except NameError:
  print ("Please complete the setup first.")

Please answer Additional Question
